/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `wp_terms` (
  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `slug` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `term_group` bigint(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (`term_id`),
  KEY `slug` (`slug`(191)),
  KEY `name` (`name`(191))
) ENGINE=InnoDB AUTO_INCREMENT=185 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (1,'Uncategorized','uncategorized',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (8,'8BIT','8bit',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (9,'alignment','alignment-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (10,'Articles','articles',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (11,'aside','aside',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (12,'audio','audio',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (13,'Business','business',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (14,'captions','captions-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (15,'categories','categories',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (16,'chat','chat',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (17,'chattels','chattels',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (18,'cienaga','cienaga',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (19,'claycold','claycold',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (20,'Codex','codex',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (21,'comments','comments-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (22,'content','content-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (23,'Corporate','corporate',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (24,'crushing','crushing',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (25,'css','css',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (26,'depo','depo',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (27,'Digital','digital',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (28,'dinarchy','dinarchy',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (29,'doolie','doolie',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (30,'dowork','dowork',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (31,'edge case','edge-case',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (32,'embeds','embeds-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (33,'energumen','energumen',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (34,'ephialtes','ephialtes',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (35,'eudiometer','eudiometer',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (36,'excerpt','excerpt-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (37,'Fail','fail',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (38,'featured image','featured-image',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (39,'figuriste','figuriste',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (40,'filler','filler',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (41,'formatting','formatting-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (42,'FTW','ftw',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (43,'Fun','fun',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (44,'gallery','gallery',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (45,'goes here','goes-here',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (46,'habergeon','habergeon',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (47,'hapless','hapless',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (48,'hartshorn','hartshorn',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (49,'hostility impregnability','hostility-impregnability',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (50,'html','html',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (51,'image','image',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (52,'impropriation','impropriation',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (53,'is','is',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (54,'jetpack','jetpack-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (55,'knave','knave',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (56,'layout','layout',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (57,'link','link',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (58,'lists','lists-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (59,'lorem','lorem',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (60,'Love','love',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (61,'Marketing','marketing',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (62,'markup','markup-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (63,'media','media',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (64,'misinformed','misinformed',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (65,'moil','moil',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (66,'more','more',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (67,'mornful','mornful',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (68,'Mothership','mothership',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (69,'Must Read','mustread',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (70,'Nailed It','nailedit',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (71,'outlaw','outlaw',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (72,'pagination','pagination',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (73,'pamphjlet','pamphjlet',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (74,'password','password-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (75,'Pictures','pictures',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (76,'pingbacks','pingbacks-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (77,'pneumatics','pneumatics',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (78,'portly portreeve','portly-portreeve',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (79,'post','post',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (80,'Post Formats','post-formats',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (81,'precipitancy','precipitancy',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (82,'privation','privation',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (83,'programme','programme',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (84,'psychological','psychological',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (85,'puncher','puncher',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (86,'quote','quote',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (87,'ramose','ramose',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (88,'read more','read-more',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (89,'readability','readability',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (90,'renegade','renegade',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (91,'retrocede','retrocede',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (92,'SEO','seo',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (93,'shortcode','shortcode',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (94,'stagnation unhorsed','stagnation-unhorsed',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (95,'standard','standard-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (96,'status','status',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (97,'sticky','sticky-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (98,'Success','success',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (99,'Swagger','swagger',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (100,'Tag A','tag-a',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (101,'Tag B','tag-b',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (102,'Tag C','tag-c',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (103,'tag1','tag1',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (104,'tag2','tag2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (105,'tag3','tag3',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (106,'Tags','tags',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (107,'template','template',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (108,'text','text',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (109,'the man','the-man',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (110,'thunderheaded','thunderheaded',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (111,'tiled','tiled',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (112,'title','title',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (113,'trackbacks','trackbacks-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (114,'twitter','twitter-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (115,'unculpable','unculpable',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (116,'Unseen','unseen',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (117,'video','video',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (118,'videopress','videopress',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (119,'withered brandnew','withered-brandnew',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (120,'WordPress','wordpress',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (121,'wordpress.tv','wordpress-tv',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (122,'xanthopsia','xanthopsia',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (123,'B2B Services','b2b-services',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (124,'Chief Product Officer','chief-product-officer',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (125,'Co-Founder &amp; CEO','co-founder-ceo',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (126,'Co-Founder &amp; CTO','co-founder-cto',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (127,'Ecommerce','ecommerce',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (128,'Featured','featured',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (129,'SEO','seo',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (130,'SMM','smm',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (131,'Test Category','test-category',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (132,'VP. Solution Architecture','vp-solution-architecture',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (133,'Appearance (Elements)','appearance-elements',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (134,'Creative (Elements)','creative-elements',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (135,'Essential (Elements)','essential-elements',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (136,'Featured Services','featured-services',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (137,'Featured Services - Menu 1 (Services)','featured-services-menu-1-services',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (138,'Featured Services - Menu 2 (Services)','featured-services-menu-2-services',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (139,'Header Menu','header-menu',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (140,'Important Links','important-links',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (141,'Minimal Header Menu','minimal-header-menu',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (142,'Modern (Elements)','modern-elements',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (143,'SEO Whitepaper (Services)','seo-whitepaper-services',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (146,'General Construction','general-construction',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (147,'Painting','painting',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (148,'Plumbing','plumbing',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (149,'Pre-Construction','pre-construction',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (150,'Company','company',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (151,'Main Menu','main-menu',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (152,'Services','services',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (153,'simple','simple',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (154,'grouped','grouped',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (155,'variable','variable',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (156,'external','external',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (157,'exclude-from-search','exclude-from-search',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (158,'exclude-from-catalog','exclude-from-catalog',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (159,'featured','featured',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (160,'outofstock','outofstock',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (161,'rated-1','rated-1',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (162,'rated-2','rated-2',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (163,'rated-3','rated-3',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (164,'rated-4','rated-4',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (165,'rated-5','rated-5',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (166,'Uncategorized','uncategorized',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (181,'News','news',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (182,'Data Science Skills','data-science-skills',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (183,'Books To Read','books-to-read',0);
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (184,'Data Visualization','data-visualization',0);
