/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `wp_usermeta` (
  `umeta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL DEFAULT 0,
  `meta_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meta_value` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`umeta_id`),
  KEY `user_id` (`user_id`),
  KEY `meta_key` (`meta_key`(191))
) ENGINE=InnoDB AUTO_INCREMENT=228 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (31,2,'nickname','admin1');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (32,2,'first_name','Mike');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (33,2,'last_name','Smith');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (34,2,'description','');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (35,2,'rich_editing','true');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (36,2,'syntax_highlighting','true');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (37,2,'comment_shortcuts','false');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (38,2,'admin_color','fresh');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (39,2,'use_ssl','0');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (40,2,'show_admin_bar_front','true');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (41,2,'locale','en_US');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (42,2,'wp_capabilities','a:1:{s:13:\"administrator\";b:1;}');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (43,2,'wp_user_level','10');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (44,2,'dismissed_wp_pointers','vc_pointers_backend_editor,plugin_editor_notice,theme_editor_notice,vc_pointers_frontend_editor');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (46,2,'wc_last_active','1641600000');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (48,2,'wp_dashboard_quick_press_last_post_id','3870');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (49,2,'community-events-location','a:1:{s:2:\"ip\";s:12:\"173.63.152.0\";}');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (52,2,'jetpack_tracks_wpcom_id','185723782');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (53,2,'wp_user-settings','libraryContent=browse&edit_element_vcUIPanelWidth=650&edit_element_vcUIPanelLeft=569px&edit_element_vcUIPanelTop=99px&editor=tinymce&mfold=o');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (54,2,'wp_user-settings-time','1650514501');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (57,2,'wysija_pref','YTowOnt9');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (74,2,'calypsoify','0');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (75,2,'_woocommerce_tracks_anon_id','woo:JLebfi7IIMuYPma+0unheYXZ');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (76,2,'wpcom_user_id','185723782');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (77,2,'wpcom_user_data','O:8:\"stdClass\":10:{s:2:\"ID\";i:185723782;s:5:\"login\";s:8:\"learndsl\";s:5:\"email\";s:22:\"ataqsceeotpp@opayq.com\";s:3:\"url\";s:24:\"https://www.learndsl.com\";s:10:\"first_name\";s:0:\"\";s:9:\"last_name\";s:0:\"\";s:12:\"display_name\";s:12:\"Ataqsceeotpp\";s:11:\"description\";s:0:\"\";s:16:\"two_step_enabled\";b:0;s:16:\"external_user_id\";i:2;}');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (80,2,'jetpack_tracks_anon_id','jetpack:xulgT7LnduFr27u9U0RdIqlm');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (83,3,'nickname','mikesmith');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (84,3,'first_name','Mike');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (85,3,'last_name','Smith');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (86,3,'description','');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (87,3,'rich_editing','true');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (88,3,'syntax_highlighting','true');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (89,3,'comment_shortcuts','false');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (90,3,'admin_color','fresh');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (91,3,'use_ssl','0');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (92,3,'show_admin_bar_front','true');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (93,3,'locale','');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (94,3,'wp_capabilities','a:1:{s:13:\"administrator\";b:1;}');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (95,3,'wp_user_level','10');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (96,3,'dismissed_wp_pointers','');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (97,3,'last_update','1599326545');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (98,2,'dismissed_template_files_notice','1');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (102,2,'wp_admin_color','classic-dark');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (103,2,'wp_wpcom_is_nav_unification_enabled','1');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (104,2,'wp_jetpack_admin_menu_link_destination','0');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (106,2,'wp_googlesitekitpersistent_initial_version','1.26.0');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (107,2,'dpsp_admin_notice_facebook_app_authorized','1');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (108,2,'_wc_plugin_framework_facebook_for_woocommerce_dismissed_messages','a:1:{s:27:\"settings_moved_to_marketing\";b:1;}');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (109,2,'wp_wpcom_site_count','1');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (111,2,'last_update','1636756580');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (115,2,'wp_jetpack_text_direction','ltr');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (117,2,'wp_jetpack_wpcom_is_rtl','0');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (121,2,'wp_googlesitekitpersistent_dismissed_tours','a:1:{i:0;s:14:\"helpVisibility\";}');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (124,2,'billing_first_name','Mike');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (125,2,'billing_last_name','Smith');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (126,2,'billing_company','Smith Publishing, LLC');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (127,2,'billing_address_1','88 East Main Street');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (128,2,'billing_address_2','PMB 505');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (129,2,'billing_city','Mendham');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (130,2,'billing_state','NJ');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (131,2,'billing_postcode','07945');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (132,2,'billing_country','US');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (133,2,'billing_email','ataqsceeotpp@opayq.com');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (134,2,'billing_phone','9173276905');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (135,2,'shipping_method','');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (140,2,'gtm4wp_user_notices_dismisses','s:156:\"a:5:{s:14:\"enter-gtm-code\";b:1;s:20:\"wc-ga-plugin-warning\";b:0;s:25:\"wc-gayoast-plugin-warning\";b:0;s:13:\"php72-warning\";b:0;s:18:\"deprecated-warning\";b:0;}\";');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (141,2,'wpcom_block_editor_nux_status','dismissed');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (177,2,'wp_googlesitekit_access_token_expires_in','3599');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (178,2,'wp_googlesitekit_access_token_created_at','1624037052');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (179,2,'wp_googlesitekit_access_token','u5OBIOsG5yL4fAYlK0UM1TdQTDkvODFQUDdoZHhrRitpZmNNZVl0Qk9ab3hiaHY2am90VE10b1l6ZWZMZFN1cHJwMnd2NHhSZE1FWnJJNWhSVlIvL2I2dEdJMUg4QkVaK1laY0c2RTVYdjVOMkxSNTBYMXViRzZlTDIyMzYrNzE2eVZKRDNnM1prV2l6OC9Xamh6VXBnK0U3eTBSbnVGWDU3YUVpMkRjWTFseWVudVdpR21CZG5MQXhjeUszNzg5eCtoMm9mQmthWFZHeElFYjdnbERRaWZoU25GOTFTbEpnMVVwSUIvRzlYK0ZNSHFiZlRoc3Jxejk4RGNTMHYzZXpwTUxMdVlldTF4Y1Mzb1JpZmtUeW14VVlUVnZzRWl2U3RHRHozQ0RDMk5HQi9XU2RsQTA4K2kyU01NMHV3Zz0=');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (180,2,'wp_googlesitekit_refresh_token','gstyv2PXOo2bLJ60sSNsIUNHK1dBbEJ5N2xaU2RYUDBTNHJNZzl2RmtMYUVBY1M1Yk1LMDBSTG43OW0xeGVOUEVlUXlJYVpSSFN6cTdiUVZWaDJPZEJVdk9qazB1NjUwZlovV1lRVVp1dEJSRHVXZTc5b1lNazBZWGZUWmlJSk5VdTFOTHYvMDBOZUhQUDFkNERFaHR3dENvYVBtZ0dXM2tMSDlFVlFBemdxU3FxWjRsemJVK05wNHROZ1QvTkhFTXlmYnp5Y2d6WVlEblRJRi9SWHVEckF4QkVCZDhIQVNLUzl4TlJTb2tHVjRsdWcxQXN5L2h4Y0lneks1QU9lUXVmbUYyYmNTTm9EZXc1T0RFcitHNmtkdkdRMWxMUWttVDRSbndtc0hDOUUwbXBKbE51Yk5jK0F6Q2xRN2VIMnArTmIweC93Mkk1Q2pIY0ZF');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (181,2,'wp_googlesitekit_auth_scopes','a:7:{i:0;s:48:\"https://www.googleapis.com/auth/siteverification\";i:1;s:6:\"openid\";i:2;s:46:\"https://www.googleapis.com/auth/userinfo.email\";i:3;s:51:\"https://www.googleapis.com/auth/tagmanager.readonly\";i:4;s:48:\"https://www.googleapis.com/auth/userinfo.profile\";i:5;s:50:\"https://www.googleapis.com/auth/analytics.readonly\";i:6;s:42:\"https://www.googleapis.com/auth/webmasters\";}');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (182,2,'wp_googlesitekit_additional_auth_scopes','a:0:{}');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (183,2,'wp_googlesitekit_profile','a:2:{s:5:\"email\";s:31:\"dataasasecondlanguage@gmail.com\";s:5:\"photo\";s:86:\"https://lh3.googleusercontent.com/a-/AOh14Gj4FxPdtOwHOsTP9g6tIwN3FvHCwAPX6XIpD4H1=s100\";}');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (184,2,'wp_googlesitekit_site_verified_meta','verified');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (185,2,'wp_googlesitekit_user_input_state','missing');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (191,2,'_woocommerce_persistent_cart_1','a:1:{s:4:\"cart\";a:0:{}}');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (194,2,'session_tokens','a:7:{s:64:\"e28f46ed2ad04b36e26e058ff35035b935c5fd1ceb140af91155e6c05d6c1f63\";a:4:{s:10:\"expiration\";i:1661624703;s:2:\"ip\";s:15:\"154.120.229.149\";s:2:\"ua\";s:133:\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 OPR/78.0.4093.147\";s:5:\"login\";i:1630088703;}s:64:\"aa4f8ab041d81c716adf52dbc2df2c5024c241bad30c8cebc7302b3d44d98464\";a:4:{s:10:\"expiration\";i:1668292065;s:2:\"ip\";s:14:\"173.63.152.191\";s:2:\"ua\";s:137:\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 OPR/80.0.4170.63\";s:5:\"login\";i:1636756065;}s:64:\"57e61c9cda0a571afea778f70c742415f0adbc16e3cfe65b7974fc5cceed9657\";a:4:{s:10:\"expiration\";i:1668292344;s:2:\"ip\";s:14:\"173.63.152.191\";s:2:\"ua\";s:160:\"Mozilla/5.0 (Macintosh; Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) WordPressDesktop/7.2.0 Chrome/89.0.4389.128 Electron/12.0.13 Safari/537.36\";s:5:\"login\";i:1636756344;}s:64:\"037adf1103e37a899cd81e4fec414e8fb3330e65442a69567affedd20ae4b8fe\";a:4:{s:10:\"expiration\";i:1668292346;s:2:\"ip\";s:14:\"173.63.152.191\";s:2:\"ua\";s:160:\"Mozilla/5.0 (Macintosh; Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) WordPressDesktop/7.2.0 Chrome/89.0.4389.128 Electron/12.0.13 Safari/537.36\";s:5:\"login\";i:1636756346;}s:64:\"4956292d8d7658dadcc7c8c9d623d9ec0cf35537fdfe6ef4b3c3ddda880fc118\";a:4:{s:10:\"expiration\";i:1668292348;s:2:\"ip\";s:14:\"173.63.152.191\";s:2:\"ua\";s:160:\"Mozilla/5.0 (Macintosh; Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) WordPressDesktop/7.2.0 Chrome/89.0.4389.128 Electron/12.0.13 Safari/537.36\";s:5:\"login\";i:1636756348;}s:64:\"e23c1d769f9d72cf2fec674484282e9556905dc1d147ea8c1119e2aea597a973\";a:4:{s:10:\"expiration\";i:1668292350;s:2:\"ip\";s:14:\"173.63.152.191\";s:2:\"ua\";s:160:\"Mozilla/5.0 (Macintosh; Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) WordPressDesktop/7.2.0 Chrome/89.0.4389.128 Electron/12.0.13 Safari/537.36\";s:5:\"login\";i:1636756350;}s:64:\"aaf378668908a0bdd31709be59e439078d249941e7d0267a38c58e37672bc150\";a:4:{s:10:\"expiration\";i:1672276680;s:2:\"ip\";s:14:\"173.63.152.191\";s:2:\"ua\";s:105:\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36\";s:5:\"login\";i:1640740680;}}');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (207,2,'_order_count','0');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (208,4,'nickname','dataasasecondlanguage');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (209,4,'first_name','');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (210,4,'last_name','');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (211,4,'description','');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (212,4,'rich_editing','true');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (213,4,'syntax_highlighting','true');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (214,4,'comment_shortcuts','false');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (215,4,'admin_color','fresh');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (216,4,'use_ssl','0');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (217,4,'show_admin_bar_front','true');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (218,4,'locale','en_US');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (219,4,'wp_capabilities','a:1:{s:6:\"author\";b:1;}');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (220,4,'wp_user_level','2');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (221,4,'dismissed_wp_pointers','');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (222,4,'wpcom_user_id','215419265');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (223,4,'wp_admin_color','classic-dark');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (224,4,'wp_wpcom_site_count','1');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (225,4,'wp_user-settings','mfold=o');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (226,4,'wp_user-settings-time','1640741306');
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES (227,4,'wp_jetpack_wpcom_is_rtl','0');
